ATO-628: add orchestration pod check dashboard
govuk-one-login/observability-configuration pull request #222
Opened 2024-06-10 15:44 UTC by isaac-GDS

# Description:

## Ticket number:
[OBS-XXX]

## Checklist:
- [ ] Is my change backwards compatible? Please include evidence
- [ ] I have tested this and added output to Jira Comment:
- [ ] Documentation added (link) Comment:

2024-06-27 08:23 UTC, chrisdodd93 requested changes

2024-06-27 08:23 UTC, chrisdodd93 commented on dashboards/orchestration/pod-check-prod.json
> +  "id": "8a5ac450-471c-40bf-b109-249c486279fd",
This line needs removing from the json file

2024-07-03 13:27 UTC, chrisdodd93 commented
Is this PR still needed @isaac-GDS, it was raised over 3 weeks ago and the changes haven't been made and I imagine there might be conflicts with the main branch now?

2024-07-04 08:20 UTC, isaac-GDS commented
This is outdated - will close this PR and raise a new one. Thanks @chrisdodd93

2024-07-04 08:20 UTC, closed without merging